# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# - https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# - https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: python

on:
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: flake8
      run: |
        flake8 .
    - name: pylint
      run: |
        pylint pyconfigurableml
    - name: pytest
      run: |
        pytest
    - name: build wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:

    # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
    - name: download wheel
      uses: actions/download-artifact@v2
      with:
        name: wheel

    - name: ls
        run: |
          ls -r

    # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    - name: test.pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: wheel
      # https://github.community/t/continue-on-error-allow-failure-ui-indication/16773
      if: success() || failure()

    - name: pypi
      if: startsWith(github.events.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        packages_dir: wheel
